[WIP] トップページのコーディング
csstalk/website pull request #11
Opened 2017-03-19 14:33 UTC by matsuoshi

まだ作業はじめたばかりですが、この方向で合ってるのかどうか、いったん確認いただけるとありがたいです

## 進捗

- トップページの Hero と About 部分のみ作業
	- About の背景画像は未着手
	- レスポンシブには一応なっていると思う
	- 色がゆっくり変わるのも実装済み、ただし色合いは未調整(ダミー)
- 開催日は /_data/data.json にデータで持たせた
	- そのため、moment.js を追加導入 (npm update が必要です)

## 確認いただきたいこと

- HTML構造 (Hero と About 以外は未完了)
- ECSS的なクラス名のつけ方など、アドバイスあればお願いします
- CSSファイルの分け方について。現状は
	- /src/assets/namespace/
		- Home
			- _Hero.css
			- _About.css
			- _Animate.css
		- SiteWide
			- _Button.css
			- _common.css (仮、パーツが増えればファイルを分けたい)

です。

2017-03-22 08:44 UTC, manabuyasuda commented on src/assets/namespace/Home/_Animate.css
> +.home-Animate_Text {
細かいところですが、`.home-Animate_Text`などのModuleは`.home-AnimateText`のほうがいいのかなと思いました。理由は`.home-Animate`というModuleの中で使う`Text`というchildNodeではなく、単体で使うものだからです。

2017-03-22 08:45 UTC, manabuyasuda commented on src/assets/namespace/Home/_Hero.css
> +  @media (--sm-down) {
メディアクエリですが、ECSSではモバイルファーストが推奨されているので、min-widthに書き直すことってできますか？

2017-03-22 08:46 UTC, manabuyasuda commented on src/assets/namespace/SiteWide/_Button.css
> +.sw-Button_alt {
`.sw-Button_alt`はどういうときに使うのかコメントがあるといいなと思いました。
それと、`.sw-Button`のchildNodeというよりは、variant（`.sw-Button-alt`）か、別のModule（`.sw-AltButton`）のようにしてもいいのかなと思いました。

2017-03-22 08:46 UTC, manabuyasuda commented on src/assets/namespace/home/_About.css
> +.home-About_Balloon {
`.home-About_Balloon`は「吹き出し」という見た目に関する情報になってしまうので、Titleのようなデザイン変更に左右されにくい名前にするのがいいと思います。

2017-03-22 08:47 UTC, manabuyasuda commented on src/assets/namespace/home/_About.css
> +
`.home-About_Text > p`というセレクタがありますが、要素セレクタへの指定は極力避けたほうがいいと思います（特にコンテンツ部分は何がくるのか分からないので）。
`.home-About_Text`自体にスタイルを指定する方法に変更できますか？

2017-03-22 08:50 UTC, manabuyasuda commented on src/index.pug
> +            h3
違う見出しというより、同じ見出しの続きなのかなと思いました。
意味合い的には「次の開催は○月○日です」みたいなことだと思うので。

2017-03-22 08:55 UTC, manabuyasuda commented on src/index.pug
> +            h3
違う見出しというより、同じ見出しの続きなのかなと思いました。
意味合い的には「次の開催は○月○日です」みたいなことだと思うので。

2017-03-22 09:00 UTC, manabuyasuda commented on src/index.pug
> +              time(
違う見出しというより、同じ見出しの続きなのかなと思いました。
意味合い的には「次の開催は○月○日です」みたいなことだと思うので。

2017-03-22 09:02 UTC, manabuyasuda requested changes
6点ほど気になったところにコメントをしています。
確認よろしくお願いします。

2017-03-22 12:53 UTC, matsuoshi commented on src/assets/namespace/home/_About.css
> +.home-About_Balloon {
ハッ、そのとおりですね、クラス名変更しますー

2017-03-22 12:54 UTC, matsuoshi commented on src/assets/namespace/Home/_Hero.css
> +  @media (--sm-down) {
…これは指摘される気がしていました… モバイルファーストに書き直しますね、
なんなら --sm-down系のカスタムメディアクエリは設定しないって手もありますね

2017-03-22 12:55 UTC, matsuoshi commented on src/assets/namespace/Home/_Animate.css
> +.home-Animate_Text {
たしかに、そのとおりだと思うので、修正しますー

2017-03-23 11:07 UTC, matsuoshi commented on src/assets/namespace/SiteWide/_Button.css
> +.sw-Button_alt {
コメントはスタイルガイドまで手がまわっていないので、ひとまず簡単なものをつけるようにします。
クラス名はそうですね、variant に変更します

2017-03-23 11:15 UTC, matsuoshi commented on src/assets/namespace/home/_About.css
> +
こちら、直接お話しもさせてもらいましたが、そのとおりですね、対応します！

2017-03-23 11:16 UTC, matsuoshi commented on src/index.pug
> +              time(
どちらも h2 の中に入れるように変更しますね

2017-03-23 11:23 UTC, matsuoshi commented
@manabuyasuda レビューありがとうございました〜
6箇所について、対応いれてpushしていますので、また見ていただけると助かります！
https://deploy-preview-11--csstalk.netlify.com/

2017-04-05 03:42 UTC, manabuyasuda approved these changes

2017-04-05 03:44 UTC, merged